#############################################
#
# This file should not be used in production.
#
#############################################
# The DB username and password, as well as the branca
# token secret, are hardcoded in this file on purpose.
version: '3'

services:
  api:
    container_name: api
    build: .
    command: "go run cmd/gtodo/main.go"
    environment: 
      MONGODB_URI: mongodb://madmin:madmin@mongo:27017
      BRANCA_SECRET: todoToDoTodostodoToDoTodostodoTo
    ports:
      - "8080:8080"
    volumes:
      - ./:/gtodo
    depends_on: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.2.0
    volumes:
      - ./db:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: madmin
      MONGO_INITDB_ROOT_PASSWORD: madmin
  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.49
    ports:
      - "8081:8081"
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: madmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: madmin
    depends_on: 
      - mongo